/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

#if defined(LIFERAY_MOBILE_SDK_FRAMEWORK) && defined(LIFERAY_MOBILE_SDK_APP)
    @import LRMobileSDK;
#else
    #import "LRBaseService.h"
#endif

/**
 * @author Bruno Farache
 */
@interface LRCommercediscountService_v73 : LRBaseService

- (NSDictionary *)addCommerceDiscountWithUserId:(long long)userId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level:(NSString *)level level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes rulesConjunction:(BOOL)rulesConjunction active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCommerceDiscountWithUserId:(long long)userId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCommerceDiscountWithUserId:(long long)userId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level:(NSString *)level level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes limitationTimesPerAccount:(int)limitationTimesPerAccount rulesConjunction:(BOOL)rulesConjunction active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)fetchByExternalReferenceCodeWithCompanyId:(long long)companyId externalReferenceCode:(NSString *)externalReferenceCode error:(NSError **)error;
- (void)deleteCommerceDiscountWithCommerceDiscountId:(long long)commerceDiscountId error:(NSError **)error CONVERT_ERROR_TO_THROWS;
- (NSDictionary *)fetchCommerceDiscountWithCommerceDiscountId:(long long)commerceDiscountId error:(NSError **)error;
- (NSDictionary *)getCommerceDiscountWithCommerceDiscountId:(long long)commerceDiscountId error:(NSError **)error;
- (NSArray *)getCommerceDiscountsWithCompanyId:(long long)companyId couponCode:(NSString *)couponCode error:(NSError **)error;
- (NSNumber *)getCommerceDiscountsCountWithCompanyId:(long long)companyId couponCode:(NSString *)couponCode error:(NSError **)error;
- (NSNumber *)getCommerceDiscountsCountByPricingClassIdWithCommercePricingClassId:(long long)commercePricingClassId title:(NSString *)title error:(NSError **)error;
- (NSArray *)searchByCommercePricingClassIdWithCommercePricingClassId:(long long)commercePricingClassId title:(NSString *)title start:(int)start end:(int)end error:(NSError **)error;
- (NSDictionary *)searchCommerceDiscountsWithCompanyId:(long long)companyId keywords:(NSString *)keywords status:(int)status start:(int)start end:(int)end sort:(LRJSONObjectWrapper *)sort error:(NSError **)error;
- (NSDictionary *)updateCommerceDiscountWithCommerceDiscountId:(long long)commerceDiscountId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateCommerceDiscountWithCommerceDiscountId:(long long)commerceDiscountId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level:(NSString *)level level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes limitationTimesPerAccount:(int)limitationTimesPerAccount rulesConjunction:(BOOL)rulesConjunction active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateCommerceDiscountWithCommerceDiscountId:(long long)commerceDiscountId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level:(NSString *)level level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes rulesConjunction:(BOOL)rulesConjunction active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateCommerceDiscountExternalReferenceCodeWithCommerceDiscountId:(long long)commerceDiscountId externalReferenceCode:(NSString *)externalReferenceCode error:(NSError **)error;
- (NSDictionary *)upsertCommerceDiscountWithUserId:(long long)userId commerceDiscountId:(long long)commerceDiscountId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)upsertCommerceDiscountWithUserId:(long long)userId commerceDiscountId:(long long)commerceDiscountId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level:(NSString *)level level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes rulesConjunction:(BOOL)rulesConjunction active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)upsertCommerceDiscountWithUserId:(long long)userId commerceDiscountId:(long long)commerceDiscountId title:(NSString *)title target:(NSString *)target useCouponCode:(BOOL)useCouponCode couponCode:(NSString *)couponCode usePercentage:(BOOL)usePercentage maximumDiscountAmount:(NSDictionary *)maximumDiscountAmount level:(NSString *)level level1:(NSDictionary *)level1 level2:(NSDictionary *)level2 level3:(NSDictionary *)level3 level4:(NSDictionary *)level4 limitationType:(NSString *)limitationType limitationTimes:(int)limitationTimes limitationTimesPerAccount:(int)limitationTimesPerAccount rulesConjunction:(BOOL)rulesConjunction active:(BOOL)active displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;

@end