/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

#if defined(LIFERAY_MOBILE_SDK_FRAMEWORK) && defined(LIFERAY_MOBILE_SDK_APP)
    @import LRMobileSDK;
#else
    #import "LRBaseService.h"
#endif

/**
 * @author Bruno Farache
 */
@interface LRCommercepricelistService_v73 : LRBaseService

- (void)setCatalogBasePriceListWithGroupId:(long long)groupId commercePriceListId:(long long)commercePriceListId type:(NSString *)type error:(NSError **)error CONVERT_ERROR_TO_THROWS;
- (NSDictionary *)fetchByExternalReferenceCodeWithCompanyId:(long long)companyId externalReferenceCode:(NSString *)externalReferenceCode error:(NSError **)error;
- (NSArray *)searchByCommercePricingClassIdWithCommercePricingClassId:(long long)commercePricingClassId name:(NSString *)name start:(int)start end:(int)end error:(NSError **)error;
- (NSDictionary *)updateExternalReferenceCodeWithCommercePriceList:(LRJSONObjectWrapper *)commercePriceList companyId:(long long)companyId externalReferenceCode:(NSString *)externalReferenceCode error:(NSError **)error;
- (NSDictionary *)fetchCommercePriceListWithCommercePriceListId:(long long)commercePriceListId error:(NSError **)error;
- (void)deleteCommercePriceListWithCommercePriceListId:(long long)commercePriceListId error:(NSError **)error CONVERT_ERROR_TO_THROWS;
- (NSDictionary *)addCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commerceCurrencyId:(long long)commerceCurrencyId parentCommercePriceListId:(long long)parentCommercePriceListId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commerceCurrencyId:(long long)commerceCurrencyId netPrice:(BOOL)netPrice parentCommercePriceListId:(long long)parentCommercePriceListId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commerceCurrencyId:(long long)commerceCurrencyId netPrice:(BOOL)netPrice parentCommercePriceListId:(long long)parentCommercePriceListId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commerceCurrencyId:(long long)commerceCurrencyId netPrice:(BOOL)netPrice type:(NSString *)type parentCommercePriceListId:(long long)parentCommercePriceListId catalogBasePriceList:(BOOL)catalogBasePriceList name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commerceCurrencyId:(long long)commerceCurrencyId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commerceCurrencyId:(long long)commerceCurrencyId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commerceCurrencyId:(long long)commerceCurrencyId parentCommercePriceListId:(long long)parentCommercePriceListId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)fetchCatalogBaseCommercePriceListByTypeWithGroupId:(long long)groupId type:(NSString *)type error:(NSError **)error;
- (NSDictionary *)fetchCommerceCatalogBasePriceListByTypeWithGroupId:(long long)groupId type:(NSString *)type error:(NSError **)error;
- (NSDictionary *)getCommercePriceListWithCommercePriceListId:(long long)commercePriceListId error:(NSError **)error;
- (NSArray *)getCommercePriceListsWithCompanyId:(long long)companyId status:(int)status start:(int)start end:(int)end orderByComparator:(LRJSONObjectWrapper *)orderByComparator error:(NSError **)error;
- (NSNumber *)getCommercePriceListsCountWithCompanyId:(long long)companyId status:(int)status error:(NSError **)error;
- (NSNumber *)getCommercePriceListsCountWithCommercePricingClassId:(long long)commercePricingClassId title:(NSString *)title error:(NSError **)error;
- (NSDictionary *)searchCommercePriceListsWithCompanyId:(long long)companyId keywords:(NSString *)keywords status:(int)status start:(int)start end:(int)end sort:(LRJSONObjectWrapper *)sort error:(NSError **)error;
- (NSNumber *)searchCommercePriceListsCountWithCompanyId:(long long)companyId keywords:(NSString *)keywords status:(int)status error:(NSError **)error;
- (NSDictionary *)updateCommercePriceListWithCommercePriceListId:(long long)commercePriceListId commerceCurrencyId:(long long)commerceCurrencyId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateCommercePriceListWithCommercePriceListId:(long long)commercePriceListId commerceCurrencyId:(long long)commerceCurrencyId parentCommercePriceListId:(long long)parentCommercePriceListId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateCommercePriceListWithCommercePriceListId:(long long)commercePriceListId commerceCurrencyId:(long long)commerceCurrencyId netPrice:(BOOL)netPrice type:(NSString *)type parentCommercePriceListId:(long long)parentCommercePriceListId catalogBasePriceList:(BOOL)catalogBasePriceList name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateCommercePriceListWithCommercePriceListId:(long long)commercePriceListId commerceCurrencyId:(long long)commerceCurrencyId netPrice:(BOOL)netPrice parentCommercePriceListId:(long long)parentCommercePriceListId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)upsertCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commercePriceListId:(long long)commercePriceListId commerceCurrencyId:(long long)commerceCurrencyId netPrice:(BOOL)netPrice type:(NSString *)type parentCommercePriceListId:(long long)parentCommercePriceListId catalogBasePriceList:(BOOL)catalogBasePriceList name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)upsertCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commercePriceListId:(long long)commercePriceListId commerceCurrencyId:(long long)commerceCurrencyId parentCommercePriceListId:(long long)parentCommercePriceListId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)upsertCommercePriceListWithGroupId:(long long)groupId userId:(long long)userId commercePriceListId:(long long)commercePriceListId commerceCurrencyId:(long long)commerceCurrencyId name:(NSString *)name priority:(double)priority displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute externalReferenceCode:(NSString *)externalReferenceCode neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;

@end