/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

#if defined(LIFERAY_MOBILE_SDK_FRAMEWORK) && defined(LIFERAY_MOBILE_SDK_APP)
    @import LRMobileSDK;
#else
    #import "LRBaseService.h"
#endif

/**
 * @author Bruno Farache
 */
@interface LRCpdefinitionService_v73 : LRBaseService

- (NSString *)getLayoutUuidWithCpDefinitionId:(long long)cpDefinitionId error:(NSError **)error;
- (NSDictionary *)updateStatusWithUserId:(long long)userId cpDefinitionId:(long long)cpDefinitionId status:(int)status serviceContext:(LRJSONObjectWrapper *)serviceContext workflowContext:(NSDictionary *)workflowContext error:(NSError **)error;
- (NSString *)getUrlTitleMapAsXmlWithCpDefinitionId:(long long)cpDefinitionId error:(NSError **)error;
- (NSDictionary *)getCpDefinitionWithCpDefinitionId:(long long)cpDefinitionId error:(NSError **)error;
- (void)deleteCpDefinitionWithCpDefinitionId:(long long)cpDefinitionId error:(NSError **)error CONVERT_ERROR_TO_THROWS;
- (NSDictionary *)copyCpDefinitionWithCpDefinitionId:(long long)cpDefinitionId groupId:(long long)groupId error:(NSError **)error;
- (NSDictionary *)addCpDefinitionWithGroupId:(long long)groupId userId:(long long)userId nameMap:(NSDictionary *)nameMap shortDescriptionMap:(NSDictionary *)shortDescriptionMap descriptionMap:(NSDictionary *)descriptionMap urlTitleMap:(NSDictionary *)urlTitleMap metaTitleMap:(NSDictionary *)metaTitleMap metaDescriptionMap:(NSDictionary *)metaDescriptionMap metaKeywordsMap:(NSDictionary *)metaKeywordsMap productTypeName:(NSString *)productTypeName ignoreSKUCombinations:(BOOL)ignoreSKUCombinations shippable:(BOOL)shippable freeShipping:(BOOL)freeShipping shipSeparately:(BOOL)shipSeparately shippingExtraPrice:(double)shippingExtraPrice width:(double)width height:(double)height depth:(double)depth weight:(double)weight cpTaxCategoryId:(long long)cpTaxCategoryId taxExempt:(BOOL)taxExempt telcoOrElectronics:(BOOL)telcoOrElectronics ddmStructureKey:(NSString *)ddmStructureKey published:(BOOL)published displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire defaultSku:(NSString *)defaultSku subscriptionEnabled:(BOOL)subscriptionEnabled subscriptionLength:(int)subscriptionLength subscriptionType:(NSString *)subscriptionType subscriptionTypeSettingsUnicodeProperties:(NSDictionary *)subscriptionTypeSettingsUnicodeProperties maxSubscriptionCycles:(long long)maxSubscriptionCycles externalReferenceCode:(NSString *)externalReferenceCode serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)addCpDefinitionWithGroupId:(long long)groupId userId:(long long)userId nameMap:(NSDictionary *)nameMap shortDescriptionMap:(NSDictionary *)shortDescriptionMap descriptionMap:(NSDictionary *)descriptionMap urlTitleMap:(NSDictionary *)urlTitleMap metaTitleMap:(NSDictionary *)metaTitleMap metaDescriptionMap:(NSDictionary *)metaDescriptionMap metaKeywordsMap:(NSDictionary *)metaKeywordsMap productTypeName:(NSString *)productTypeName ignoreSKUCombinations:(BOOL)ignoreSKUCombinations shippable:(BOOL)shippable freeShipping:(BOOL)freeShipping shipSeparately:(BOOL)shipSeparately shippingExtraPrice:(double)shippingExtraPrice width:(double)width height:(double)height depth:(double)depth weight:(double)weight cpTaxCategoryId:(long long)cpTaxCategoryId taxExempt:(BOOL)taxExempt telcoOrElectronics:(BOOL)telcoOrElectronics ddmStructureKey:(NSString *)ddmStructureKey published:(BOOL)published displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire defaultSku:(NSString *)defaultSku subscriptionEnabled:(BOOL)subscriptionEnabled subscriptionLength:(int)subscriptionLength subscriptionType:(NSString *)subscriptionType subscriptionTypeSettingsUnicodeProperties:(NSDictionary *)subscriptionTypeSettingsUnicodeProperties maxSubscriptionCycles:(long long)maxSubscriptionCycles deliverySubscriptionEnabled:(BOOL)deliverySubscriptionEnabled deliverySubscriptionLength:(int)deliverySubscriptionLength deliverySubscriptionType:(NSString *)deliverySubscriptionType deliverySubscriptionTypeSettingsUnicodeProperties:(NSDictionary *)deliverySubscriptionTypeSettingsUnicodeProperties deliveryMaxSubscriptionCycles:(long long)deliveryMaxSubscriptionCycles externalReferenceCode:(NSString *)externalReferenceCode serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (void)deleteAssetCategoryCpDefinitionWithCpDefinitionId:(long long)cpDefinitionId categoryId:(long long)categoryId serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error CONVERT_ERROR_TO_THROWS;
- (NSDictionary *)fetchCpDefinitionWithCpDefinitionId:(long long)cpDefinitionId error:(NSError **)error;
- (NSDictionary *)fetchCpDefinitionByCProductExternalReferenceCodeWithCompanyId:(long long)companyId externalReferenceCode:(NSString *)externalReferenceCode error:(NSError **)error;
- (NSDictionary *)fetchCpDefinitionByCProductIdWithCProductId:(long long)cProductId error:(NSError **)error;
- (NSArray *)getCpDefinitionsWithGroupId:(long long)groupId status:(int)status start:(int)start end:(int)end orderByComparator:(LRJSONObjectWrapper *)orderByComparator error:(NSError **)error;
- (NSNumber *)getCpDefinitionsCountWithGroupId:(long long)groupId status:(int)status error:(NSError **)error;
- (NSDictionary *)searchCpDefinitionsWithCompanyId:(long long)companyId keywords:(NSString *)keywords status:(int)status start:(int)start end:(int)end sort:(LRJSONObjectWrapper *)sort error:(NSError **)error;
- (NSDictionary *)searchCpDefinitionsWithCompanyId:(long long)companyId keywords:(NSString *)keywords filterFields:(NSString *)filterFields filterValues:(NSString *)filterValues start:(int)start end:(int)end sort:(LRJSONObjectWrapper *)sort error:(NSError **)error;
- (NSDictionary *)updateCpDefinitionWithCpDefinitionId:(long long)cpDefinitionId nameMap:(NSDictionary *)nameMap shortDescriptionMap:(NSDictionary *)shortDescriptionMap descriptionMap:(NSDictionary *)descriptionMap urlTitleMap:(NSDictionary *)urlTitleMap metaTitleMap:(NSDictionary *)metaTitleMap metaDescriptionMap:(NSDictionary *)metaDescriptionMap metaKeywordsMap:(NSDictionary *)metaKeywordsMap ignoreSKUCombinations:(BOOL)ignoreSKUCombinations ddmStructureKey:(NSString *)ddmStructureKey published:(BOOL)published displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateCpDefinitionAccountGroupFilterWithCpDefinitionId:(long long)cpDefinitionId enable:(BOOL)enable error:(NSError **)error;
- (NSDictionary *)updateCpDefinitionCategorizationWithCpDefinitionId:(long long)cpDefinitionId serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateCpDefinitionChannelFilterWithCpDefinitionId:(long long)cpDefinitionId enable:(BOOL)enable error:(NSError **)error;
- (NSDictionary *)updateShippingInfoWithCpDefinitionId:(long long)cpDefinitionId shippable:(BOOL)shippable freeShipping:(BOOL)freeShipping shipSeparately:(BOOL)shipSeparately shippingExtraPrice:(double)shippingExtraPrice width:(double)width height:(double)height depth:(double)depth weight:(double)weight serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateSubscriptionInfoWithCpDefinitionId:(long long)cpDefinitionId subscriptionEnabled:(BOOL)subscriptionEnabled subscriptionLength:(int)subscriptionLength subscriptionType:(NSString *)subscriptionType subscriptionTypeSettingsUnicodeProperties:(NSDictionary *)subscriptionTypeSettingsUnicodeProperties maxSubscriptionCycles:(long long)maxSubscriptionCycles serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)updateSubscriptionInfoWithCpDefinitionId:(long long)cpDefinitionId subscriptionEnabled:(BOOL)subscriptionEnabled subscriptionLength:(int)subscriptionLength subscriptionType:(NSString *)subscriptionType subscriptionTypeSettingsUnicodeProperties:(NSDictionary *)subscriptionTypeSettingsUnicodeProperties maxSubscriptionCycles:(long long)maxSubscriptionCycles deliverySubscriptionEnabled:(BOOL)deliverySubscriptionEnabled deliverySubscriptionLength:(int)deliverySubscriptionLength deliverySubscriptionType:(NSString *)deliverySubscriptionType deliverySubscriptionTypeSettingsUnicodeProperties:(NSDictionary *)deliverySubscriptionTypeSettingsUnicodeProperties deliveryMaxSubscriptionCycles:(long long)deliveryMaxSubscriptionCycles error:(NSError **)error;
- (NSDictionary *)updateTaxCategoryInfoWithCpDefinitionId:(long long)cpDefinitionId cpTaxCategoryId:(long long)cpTaxCategoryId taxExempt:(BOOL)taxExempt telcoOrElectronics:(BOOL)telcoOrElectronics error:(NSError **)error;
- (NSDictionary *)upsertCpDefinitionWithGroupId:(long long)groupId userId:(long long)userId nameMap:(NSDictionary *)nameMap shortDescriptionMap:(NSDictionary *)shortDescriptionMap descriptionMap:(NSDictionary *)descriptionMap urlTitleMap:(NSDictionary *)urlTitleMap metaTitleMap:(NSDictionary *)metaTitleMap metaDescriptionMap:(NSDictionary *)metaDescriptionMap metaKeywordsMap:(NSDictionary *)metaKeywordsMap productTypeName:(NSString *)productTypeName ignoreSKUCombinations:(BOOL)ignoreSKUCombinations shippable:(BOOL)shippable freeShipping:(BOOL)freeShipping shipSeparately:(BOOL)shipSeparately shippingExtraPrice:(double)shippingExtraPrice width:(double)width height:(double)height depth:(double)depth weight:(double)weight cpTaxCategoryId:(long long)cpTaxCategoryId taxExempt:(BOOL)taxExempt telcoOrElectronics:(BOOL)telcoOrElectronics ddmStructureKey:(NSString *)ddmStructureKey published:(BOOL)published displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire defaultSku:(NSString *)defaultSku subscriptionEnabled:(BOOL)subscriptionEnabled subscriptionLength:(int)subscriptionLength subscriptionType:(NSString *)subscriptionType subscriptionTypeSettingsUnicodeProperties:(NSDictionary *)subscriptionTypeSettingsUnicodeProperties maxSubscriptionCycles:(long long)maxSubscriptionCycles deliverySubscriptionEnabled:(BOOL)deliverySubscriptionEnabled deliverySubscriptionLength:(int)deliverySubscriptionLength deliverySubscriptionType:(NSString *)deliverySubscriptionType deliverySubscriptionTypeSettingsUnicodeProperties:(NSDictionary *)deliverySubscriptionTypeSettingsUnicodeProperties deliveryMaxSubscriptionCycles:(long long)deliveryMaxSubscriptionCycles externalReferenceCode:(NSString *)externalReferenceCode serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (NSDictionary *)upsertCpDefinitionWithGroupId:(long long)groupId userId:(long long)userId nameMap:(NSDictionary *)nameMap shortDescriptionMap:(NSDictionary *)shortDescriptionMap descriptionMap:(NSDictionary *)descriptionMap urlTitleMap:(NSDictionary *)urlTitleMap metaTitleMap:(NSDictionary *)metaTitleMap metaDescriptionMap:(NSDictionary *)metaDescriptionMap metaKeywordsMap:(NSDictionary *)metaKeywordsMap productTypeName:(NSString *)productTypeName ignoreSKUCombinations:(BOOL)ignoreSKUCombinations shippable:(BOOL)shippable freeShipping:(BOOL)freeShipping shipSeparately:(BOOL)shipSeparately shippingExtraPrice:(double)shippingExtraPrice width:(double)width height:(double)height depth:(double)depth weight:(double)weight cpTaxCategoryId:(long long)cpTaxCategoryId taxExempt:(BOOL)taxExempt telcoOrElectronics:(BOOL)telcoOrElectronics ddmStructureKey:(NSString *)ddmStructureKey published:(BOOL)published displayDateMonth:(int)displayDateMonth displayDateDay:(int)displayDateDay displayDateYear:(int)displayDateYear displayDateHour:(int)displayDateHour displayDateMinute:(int)displayDateMinute expirationDateMonth:(int)expirationDateMonth expirationDateDay:(int)expirationDateDay expirationDateYear:(int)expirationDateYear expirationDateHour:(int)expirationDateHour expirationDateMinute:(int)expirationDateMinute neverExpire:(BOOL)neverExpire defaultSku:(NSString *)defaultSku subscriptionEnabled:(BOOL)subscriptionEnabled subscriptionLength:(int)subscriptionLength subscriptionType:(NSString *)subscriptionType subscriptionTypeSettingsUnicodeProperties:(NSDictionary *)subscriptionTypeSettingsUnicodeProperties maxSubscriptionCycles:(long long)maxSubscriptionCycles externalReferenceCode:(NSString *)externalReferenceCode serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error;
- (void)updateCpDisplayLayoutWithCpDefinitionId:(long long)cpDefinitionId layoutUuid:(NSString *)layoutUuid serviceContext:(LRJSONObjectWrapper *)serviceContext error:(NSError **)error CONVERT_ERROR_TO_THROWS;

@end